### ISSUE TITLE
Email uniqueness is required, but its presence isn't

### ISSUE THREAD

**Issue by ilya-konanykhin** [spacemunkay/BikeShed#120]
Found a bug: email is required to be not null in DB and also has a unique constraint on it. That is, when someone tries to enter empty email (which shouldn't bother us at all) a unique constraint violation error pops up from the database, since there is obviously some user with empty email.

Either we should let emails be empty (NULL) and thus not covered by unique constraint, or require them to be nonempty.

**Comment by ilya-konanykhin** [comment]
(This happens because empty emails get transformed into empty string '' which is then checked for existence in the databse.)

**Comment by spacemunkay** [comment]
Saw this bug as well.  I'm thinking we let the emails be NULL.
